spring:
  application:
    name: ${APPLICATION_NAME:eureka}
  config:
    import: "configserver:"
  cloud:
    config:
      uri: ${CONFIG_URL:http://localhost:8095}


server:
  port: 8761
  ssl:
    enabled: true
    key-store: classpath:keystore/server.jks
    key-store-password: certificate
    key-alias: localhost
#    trust-store: classpath:keystore/trust.jks
#    trust-store-password: password
    key-store-type: JKS
#    trust-store-type: JKS
