spring:
  application:
    name: eureka


server:
  port: 7777
  ssl:
    enabled: true
    key-store: classpath:keystore/server.jks
    key-store-password: certificate
    key-alias: localhost
    trust-store: classpath:keystore/trust.jks
    trust-store-password: password
    key-store-type: JKS
    trust-store-type: JKS
