spring:
  application:
    name: ${APPLICATION_NAME:configuration}
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URL:https://github.com/TivM/config-server}
          default-label: ${GIT_BRANCH:main}
          clone-on-start: true
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: https://localhost:8761/eureka
    fetch-registry: false

server:
  port: 8095
#  ssl:
#    enabled: true
#    key-store: classpath:keystore/server.jks
#    key-store-password: certificate
#    key-alias: localhost
#    trust-store: classpath:keystore/trust.jks
#    trust-store-password: password
#    key-store-type: JKS
#    trust-store-type: JKS
